CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 1000),
	image_path TEXT CHECK (length(image_path) <= 255),
	privacy_type INTEGER NOT NULL DEFAULT 0 CHECK (privacy_type IN (0, 1, 2)),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
