CREATE TABLE IF NOT EXISTS group_invitations (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	group_id INTEGER NOT NULL,
	inviter_id INTEGER NOT NULL,
	invitee_id INTEGER NOT NULL,
	pending BOOLEAN NOT NULL DEFAULT 1,
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
	FOREIGN KEY (inviter_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (invitee_id) REFERENCES users(id) ON DELETE CASCADE
);