CREATE TABLE IF NOT EXISTS group_comments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	group_post_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	username TEXT NOT NULL,
	content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 1000),
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (group_post_id) REFERENCES group_posts(id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);