CREATE TABLE IF NOT EXISTS event_options (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	event_id INTEGER NOT NULL,
	option_text TEXT NOT NULL CHECK (length(option) BETWEEN 1 AND 100),
	FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);