import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { CookiesProvider } from "next-client-cookies/server";
import { getCookies } from "next-client-cookies/server";
import { WebSocketProvider } from "./context/WebSocketContext";
import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export var metadata: Metadata = {
    title: "Social Network",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
                {/* <header><Navbar /></header> */}
                <CookiesProvider>
                    <WebSocketProvider>
                        <main>{children}</main>
                    </WebSocketProvider>
                </CookiesProvider>
            </body>
        </html>
    );
}
